<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> 
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .container {
            margin-top: 40px;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="col-sm-4">
            
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Upload a file</h3>
                        
                    <form id="formFiles" action="/upload" method="post" enctype="multipart/form-data">
                            
                        <div class="form-group">
                            <label>Select files to multiple upload:</label>
                            <input type="file" name="multiple[]" multiple>
                        </div>

                        <button type="submit">Upload</button>

                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Lista de Arquivos</h3>
                    <div id="listFiles"  class="list-group"></div>
                </div>
            </div>
        </div>

    </div>
        
    <div class="col-sm-8">
        <div id="Player">
            <video controls></video>
        </div>
    </div>
                
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="/js/lib/jquery-form.min.js"></script> 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script data-main="/js/app" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.20/require.min.js"></script>
                
</body>
</html>
