<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> 
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>

        <main class="container">

            <div class="col-sm-8 col-sm-offset-2" style="height: 300px; overflow-y: auto;">
                <h3>Lista de Arquivos</h3>
                <ul id="listFiles">
                </ul>
            </div>
            
            <div class="col-sm-8 col-sm-offset-2">

                <h3>Upload a file</h3>

                <form id="formUpload" action="/upload" method="post" enctype="multipart/form-data">
                    
                    <div class="form-group">
                        <label>Select file to upload:</label>
                        <input type="file" name="simple">
                    </div>

                    <div class="form-group">
                        <label>Select files to multiple upload:</label>
                        <input type="file" name="multiple[]" multiple>
                    </div>

                    <button type="submit">Upload</button>

                </form>

            </div>

        </main>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="/js/lib/jquery-form.min.js"></script> 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script data-main="/js/app" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.20/require.min.js"></script>
                
    </body>
</html>
